services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate && python manage.py loaddata ./fixtures/new_all_data.json && python manage.py runserver 0.0.0.0:8000 --insecure"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13.15-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: