# Generated by Django 4.2.11 on 2024-05-27 00:18

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='options',
            field=django_jsonform.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
