# Generated by Django 4.2.11 on 2024-04-06 22:32

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='options',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
