# Generated by Django 4.2.11 on 2024-05-27 00:22

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_description_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='options',
            field=django_jsonform.models.fields.JSONField(default=dict, verbose_name='Опции'),
        ),
    ]
