# Generated by Django 4.2.11 on 2024-05-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
