# Generated by Django 4.2.11 on 2024-05-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
