# Generated by Django 4.2.11 on 2024-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_payment',
            field=models.SmallIntegerField(choices=[(0, 'Оплата картой'), (1, 'Оплата наличными')], default=0),
        ),
    ]
