# Generated by Django 4.2.11 on 2024-05-23 17:13

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=django_jsonform.models.fields.JSONField(default=None, verbose_name='Дополнительные параметры'),
        ),
    ]
