# Generated by Django 4.2.11 on 2024-05-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_is_paid_order_payment_on_get_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_on_get',
        ),
    ]
